# Generated by Django 6.0.3 on 2026-03-29 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='nome',
            new_name='Codigo',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='descricao',
            new_name='Descricao',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='preco',
            new_name='Lote',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='quantidade',
            new_name='Quantidade',
        ),
    ]
