# Generated by Django 6.0.3 on 2026-03-29 21:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_rename_nome_material_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
