# Generated by Django 6.0.3 on 2026-03-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_material_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='Obra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
