# Generated by Django 6.0.3 on 2026-04-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_material_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='Preco_Unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='Lote',
            field=models.CharField(max_length=100),
        ),
    ]
